name: star_wars_project
description: Star Wars project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  http:
  provider: ^5.0.0
  async: ^2.5.0
  connectivity: ^3.0.3
  bordered_text: ^1.0.1
  google_fonts: ^2.0.0
  flutter_launcher_icons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/darkLogo710x599.png"
  image_path_ios: "assets/darkLogo710x599.png"
  ios: true
  android: true

flutter:
  assets:
    - assets/
  uses-material-design: true